version: '3.8'

services:
  frontend:
    container_name: REACTJS_SERVER_CONTAINER
    build: '.'

    volumes:
      - ./:/react-app
    depends_on:
      - server
      - db
    links:
      - server
    ports:
      - '3000:3000'

  server:
    container_name: NODEJS_SERVER_CONTAINER
    build: '.'
    
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '9000:9000'

  db:
    image: 'mongo'
    container_name: MONGODB_CONTAINER
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db